// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_f2xfDScFYiJdVsBr6Xhrd-hVrRGrlP0',
    appId: '1:629900837240:web:5edf30baf644147d24c88d',
    messagingSenderId: '629900837240',
    projectId: 'memory-app-server',
    authDomain: 'memory-app-server.firebaseapp.com',
    storageBucket: 'memory-app-server.firebasestorage.app',
    measurementId: 'G-3JG3RPPNNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLZOVaRrnmRX3MRrfWMKeBmtFlB0VaNs',
    appId: '1:629900837240:android:2d4dfde780ed14e424c88d',
    messagingSenderId: '629900837240',
    projectId: 'memory-app-server',
    storageBucket: 'memory-app-server.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlasNkTyFm9EqfdoDp1VuGqCquLFKrYaM',
    appId: '1:629900837240:ios:f7b50a73a0bf441f24c88d',
    messagingSenderId: '629900837240',
    projectId: 'memory-app-server',
    storageBucket: 'memory-app-server.firebasestorage.app',
    iosBundleId: 'com.memory.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlasNkTyFm9EqfdoDp1VuGqCquLFKrYaM',
    appId: '1:629900837240:ios:b8822c51068d942e24c88d',
    messagingSenderId: '629900837240',
    projectId: 'memory-app-server',
    storageBucket: 'memory-app-server.firebasestorage.app',
    iosBundleId: 'com.memory.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_f2xfDScFYiJdVsBr6Xhrd-hVrRGrlP0',
    appId: '1:629900837240:web:69323078b6c6b8ec24c88d',
    messagingSenderId: '629900837240',
    projectId: 'memory-app-server',
    authDomain: 'memory-app-server.firebaseapp.com',
    storageBucket: 'memory-app-server.firebasestorage.app',
    measurementId: 'G-KZC1DZSQ8K',
  );
}